uploads = []
generated = []

[[outputs]]
id = "lC8tRET3JyrnnnLDAn6e7"
uri = "file://headout-orm-rca.zip"
type = "unspecified"
title = "Headout ORM RCA — Source Code"

[[outputs]]
id = "hWYN13b_loFa0jv-8njQw"
uri = "file://exports/orm-rca-v2-changed-files.zip"
type = "unspecified"
title = "ORM RCA v2 — all changed files"
