"""Case findings with their pairwise overlap, so a threshold can be measured.

The dedupe collapses a reworded repeat when containment reaches
`_SAME_FACT_OVERLAP`. Setting that number by guessing is how it has been wrong
twice. This prints every finding on a real card and the overlap between every
pair, so the threshold can be put in the GAP between "same fact" and
"different fact" instead of picked.

    python3 scripts/trace_findings.py tp_abc123        # a review id
    python3 scripts/trace_findings.py --bid 32885089   # or a booking id

Read-only: it reads the stored draft and prints. No Zendesk, no model call,
nothing written.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))



def _stamp_banner(draft) -> str:
    """Loud, first, and on every tracer that reads a stored draft.

    A diagnostic reports a STORED card against the rules in the code running
    now. Where the two disagree the report is about a card that no longer
    exists — and reads exactly like one about a card that does. Three round
    trips went on one review because `gaps: []` from a prompt that never asked
    for gaps prints the same words as `gaps: []` from a clean case.

    `prompt_stamp_state` is imported, not restated: it moves with the prompt
    body, which is the whole point.
    """
    from server.prompts import prompt_stamp_state, RCA_PROMPT_VERSION
    state = prompt_stamp_state(getattr(draft, "rca_prompt_version", ""))
    if state == "current":
        return ""
    head = ("!!! THIS DRAFT PREDATES THE RUNNING PROMPT !!!" if state == "stale"
            else "!!! THIS DRAFT CARRIES NO PROMPT STAMP !!!")
    why = ("  It was generated by a different set of questions, so nothing "
           "below\n  is this build's answer for this case — including any "
           "EMPTY section,\n  which here means 'not asked', not 'nothing "
           "found'.\n  REGENERATE THE RCA, then run this again.")
    ver = ""
    if state == "stale":
        ver = (f"\n  stamped {getattr(draft, 'rca_prompt_version', '')}"
               f"\n  running {RCA_PROMPT_VERSION}")
    return f"\n{'=' * 72}\n  {head}{ver}\n{why}\n{'=' * 72}"

def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("review_id", nargs="?", help="review id (tp_...)")
    ap.add_argument("--bid", help="booking id, if you do not have the review id")
    ap.add_argument("--floor", type=float, default=0.25,
                    help="only print pairs at or above this overlap")
    a = ap.parse_args(argv)
    if not a.review_id and not a.bid:
        ap.error("give a review id or --bid")

    from server.db import SessionLocal, RcaDraft
    from server.services.rca_v4_validate import _case_finding_key, _SAME_FACT_OVERLAP
    from server.services.rca_v4_validate import _tokens
    # THE REAL PREDICATES, IMPORTED — not restated here. A tracer that rebuilds
    # the rule it is checking reports on its own copy, and this has already
    # cost a session once: trace_shaping.py rebuilt the shaping path and called
    # a fixed bug broken. When the fold changes, these move with it.
    from server.services.rca_v4_validate import (_finding_minute,
                                                 _SAME_MINUTE_OVERLAP)

    s = SessionLocal()
    try:
        q = s.query(RcaDraft)
        d = (q.filter(RcaDraft.review_id == a.review_id).first() if a.review_id
             else next((r for r in q.all()
                        if str((r.booking or {}).get("id") or "") == str(a.bid)), None))
        if not d:
            print("No draft found for that id.")
            return 1
        print(_stamp_banner(d), end="")
        v3 = d.rca_v3 if isinstance(d.rca_v3, dict) else {}
        rows = ((v3.get("what_went_wrong") or {}).get("case_findings")) or []
        print(f"\n=== CASE FINDINGS ON {d.review_id}: {len(rows)} ===")
        texts = []
        for i, r in enumerate(rows):
            t = (r or {}).get("text") if isinstance(r, dict) else str(r)
            backs = (r or {}).get("backs_claim") if isinstance(r, dict) else None
            ref = (r or {}).get("ref") if isinstance(r, dict) else None
            texts.append(t or "")
            tag = "narrative" if backs is None else f"backs claim {backs}"
            _t = (r or {}).get("time") if isinstance(r, dict) else None
            # THE FIELD THE ORDER COMES FROM. Every finding on a real card came
            # back with time: null, so §1 was the model's writing order wearing
            # a chronology's clothes. Printed first because it is the thing to
            # look at.
            _tt = str(_t) if _t else "NO TIME — cannot be placed"
            print(f"\n  [{i:>2}] {_tt:<28} {tag}{'  ' + str(ref) if ref else ''}")
            print(f"       {' '.join(str(t or '').split())}")

        _undated = sum(1 for r in rows
                       if isinstance(r, dict) and not (r or {}).get("time"))
        print(f"\n  {_undated} of {len(rows)} carry NO TIME"
              + (" — this section is not a chronology, it is the order the "
                 "model wrote them in" if _undated == len(rows) else ""))

        print(f"\n=== PAIRWISE OVERLAP ===")
        print(f"  wording alone folds at {_SAME_FACT_OVERLAP}; two rows at the "
              f"SAME MINUTE fold at {_SAME_MINUTE_OVERLAP}, because the clock "
              f"has already done most of the work.")
        print("  containment = shared significant words / the shorter row's words\n")
        pairs = []
        for i in range(len(texts)):
            for j in range(i + 1, len(texts)):
                a_, b_ = _tokens(texts[i]), _tokens(texts[j])
                if not a_ or not b_:
                    continue
                ov = len(a_ & b_) / max(1, min(len(a_), len(b_)))
                if ov >= a.floor:
                    pairs.append((ov, i, j, sorted(a_ & b_)))
        if not pairs:
            print(f"  no pair reaches {a.floor}. Nothing here reads as a repeat.")
        _minutes = [_finding_minute(r) if isinstance(r, dict) else ""
                    for r in rows]
        for ov, i, j, shared in sorted(pairs, reverse=True):
            # WHICH BAR APPLIES TO THIS PAIR, and say which one it was. The two
            # rules give different answers on the same number, so a bare
            # "kept apart" beside 0.57 is unreadable without knowing whether
            # the minutes agreed.
            _same_min = bool(_minutes[i]) and _minutes[i] == _minutes[j]
            bar = _SAME_MINUTE_OVERLAP if _same_min else _SAME_FACT_OVERLAP
            why = (f"same minute {_minutes[i]}, bar {bar}" if _same_min
                   else (f"different minutes, bar {bar}"
                         if _minutes[i] and _minutes[j]
                         else f"one or both undated, bar {bar}"))
            state = "FOLDS" if ov >= bar else "kept apart"
            print(f"  {ov:.2f}  [{i:>2}] x [{j:>2}]  {state:<10}  ({why})")
            print(f"        shared: {', '.join(shared)}")
        print("\nWhat to read here:")
        print("  These are the rows that SURVIVED. A pair marked FOLDS here is")
        print("  one the rule would now catch — it is on screen because it was")
        print("  written before the rule, or because the two rows entered by a")
        print("  path the fold does not cover.")
        print("  A pair you consider a DUPLICATE that says 'kept apart' is the")
        print("  bar being too high — its number is the ceiling.")
        print("  A pair you consider DIFFERENT that says 'FOLDS' is the bar")
        print("  being too low — its number is the floor.")
        print("  Check the reason in brackets first. A duplicate 'kept apart'")
        print("  at 'one or both undated' is not a threshold problem: it is a")
        print("  MISSING TIME, and the fix is upstream in the prompt.")
        return 0
    finally:
        s.close()


if __name__ == "__main__":
    sys.exit(main())
